import clsx from "clsx";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import ThemeProvider from "@/lib/hooks/ThemeProvider";

import Footer from "./components/Footer";
import Header from "./components/Header";

import "./globals.css";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: "Next App2!",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="ru"
      className={clsx(
        "scroll-pt-16 scroll-smooth",
        inter.variable,
        "antialiased",
      )}
      suppressHydrationWarning
    >
      <body className="">
        <ThemeProvider>
          <header className="sticky top-0 z-50 col-span-3 row-span-1 row-start-1">
            <Header />
          </header>
          {children}
          <footer className="col-span-3 row-span-1 row-start-3">
            <Footer />
          </footer>{" "}
        </ThemeProvider>
      </body>
    </html>
  );
}
