import type { Metadata } from "next";
import Footer from "./components/Footer";
import { Inter } from "next/font/google";
import "./globals.css";

import ThemeProvider from "@/lib/hooks/ThemeProvider";
import ThemeSwitcher from "@/app/components/ThemeSwitcher";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next App2!",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="ru"
      className="scroll-pt-16 scroll-smooth"
      suppressHydrationWarning
    >
      <body className="   ">
        <ThemeProvider>
          <ThemeSwitcher />
          {children}
          <footer className="col-span-3 row-span-1 row-start-3">
            <Footer />
          </footer>{" "}
        </ThemeProvider>
      </body>
    </html>
  );
}
